site_name: Le contexte CUB Anvers
site_url: https://Andy-Remy.github.io/Anvers
theme:
  name: material
  logo: media/CUB.png
  favicon: media/CUB.png
  language: fr
  features:
    - content.code.copy
  palette:
    primary: green
    accent: teal

nav:
  - Accueil: index.md

  - CUB Anvers:
      - Documentations:
          - Cybersécurité:
              - Situation n°1 - Cyber: documentations/Cybersécurité/Situation n°1 Cyber.md
              - Situation n°2 - Cyber: documentations/Cybersécurité/Situation n°2 Cyber.md
              - Situation n°3 - Cyber: documentations/Cybersécurité/Situation n°3 Cyber.md
              - Situation n°4 - Cyber: documentations/Cybersécurité/Situation n°4 Cyber.md
              - Situation n°5 - Cyber: documentations/Cybersécurité/Situation n°5 Cyber.md
              - Situation n°6 - Cyber: documentations/Cybersécurité/Situation n°6 Cyber.md
          - DNS:
              - DNS0 - Récursif - CUB: documentations/DNS/CUB - Serveur DNS Recursif.md
              - DNS1 - Récursif - CUB: documentations/DNS/CUB - Serveur DNS1 Recursif.md
              - NS0 - Autorité - CUB: documentations/DNS/CUB - Serveur DNS Autorité.md
              - NS1 - Esclave - CUB: documentations/DNS/CUB - Serveur DNS1 esclave.md
          - Situations:
              - Situation n°O - CUB: documentations/Situations/Situation n°0 CUB – Plan d'adressage - Schéma logique & physique - Table de routage - NAT.md
              - Situation n°1 - CUB: documentations/Situations/Situation n°1 CUB.md
              - Situation n°2 - CUB: documentations/Situations/Situation n°2 CUB.md
              - Situation n°3 - CUB: documentations/Situations/Situation n°3 CUB.md
              - Situation n°4 - CUB: documentations/Situations/Situation n°4 CUB.md
              - Situation n°5 - CUB: documentations/Situations/Situation n°5 CUB.md
          - Configs:
              - Switch 3 - CUB: documentations/Configs/Config Switch 3.md
              - Switch 2 - CUB: documentations/Configs/Config Switch 2.md
      
markdown_extensions:
  - toc:
      permalink: true
  - tables
  - admonition
  - codehilite
  - footnotes
  - attr_list